name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what's happening.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the behavior?
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Deskapp version
      placeholder: e.g. 0.1.0
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.12.4
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell, and any relevant environment details
      placeholder: e.g. Ubuntu 22.04, bash 5.2
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs or stack traces (use backticks for code blocks)
      render: shell

