name: Release Drafter

on:
  push:
    branches: [master, main]
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled, closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

